theme: jekyll-theme-slate

# Profile:
title: Patrick Ernandes
name: Patrick Ernandes
description: >
    # Infraestrutura em TI
baseurl: "/site"
url: "http://ernandes.info"
#url: "https://github.com/patrickernandes/site"

# Social:
facebook: #Add your Facebook
twitter_username: patrickernandes
github_username: patrickernandes

# Contact:
email: suporte@ernandes.info

# markdown model:
markdown: kramdown

#links:
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://ernandes.info"


