theme: jekyll-theme-slate

# Profile:
title: Patrick Ernandes
name: Patrick Ernandes
description: >
    Infraestrutura em TI
baseurl: "/site"
#url: "https://patrickernandes.github.io/site/" #the base hostname & protocol for your site.
url: "https://github.com/patrickernandes/site"

# Social:
facebook: #Add your Facebook
twitter: patrickernandes
github: patrickernandes

# Contact:
email: suporte@ernandes.info

# markdown model:
markdown: kramdown

